[package]
name = "advent2023-04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
simple_logger = "4.3.3"

[[bin]]
name = "advent2023-04"
path = "main.rs"
